version: '3'
services:

  python:
    container_name: python
    build: ./build/python
    volumes:
    - /var/lib/python
    links:
    - mysql
    - redis
    
  ### MySQL Container
  mysql:
    container_name: mysql
    build: ./build/mysql
    volumes:
      - /var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "3306:3306"
      
  ### Redis Container
  redis:
    image: redis
    expose:
        - "6379"
     
  ### Workspace Utilities Container
  workspace:
    build: ./build/workspace
    volumes:
      - ./src:/var/www
    links:
      - mysql
      - redis
    tty: true

volumes:
  src:
