version: '3'
services:
  ### Python Workspace Container
 python:
    container_name: python
    build: ./build/python
    volumes:
      - ./src:/var/www
    tty: true
 ### Tensorflow lib Container
 tensorflow:
    container_name: tensorflow
    build: ./build/tensorflow
    volumes:
       - ./src:/var/www
    ports:
      - 8888:8888
 ### Tensorflow Boarch Container
 tensorboard:
    container_name: tensorboard
    build: ./build/tensorflow
    volumes:
       - ./src:/var/www
    ports:
      - 6006:6006
    command: tensorboard --logdir=/var/www/graphs

volumes:
  src:
